import { PDFDocument } from "@cantoo/pdf-lib";

/** Parse generated bytes and verify the expected page count before reporting success. */
export async function validatePdfBytes(
  bytes: Uint8Array,
  expectedPages: number,
): Promise<void> {
  if (
    bytes.byteLength === 0 ||
    !Number.isInteger(expectedPages) ||
    expectedPages < 1
  ) {
    throw new Error("PDF output is empty or has an invalid page count");
  }
  const parsed = await PDFDocument.load(bytes);
  if (parsed.getPageCount() !== expectedPages)
    throw new Error("PDF output page count does not match");
}
